// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkNes {
    
    
    public partial class FrontPanel {
        
        private Gtk.Expander expander1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ToggleButton ejectButton;
        
        private Gtk.ToggleButton powerButton;
        
        private Gtk.CheckButton checkPause;
        
        private Gtk.Expander expander2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView txtRomInfo;
        
        private Gtk.Label GtkLabel4;
        
        private Gtk.Label GtkLabel3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkNes.FrontPanel
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkNes.FrontPanel";
            // Container child GtkNes.FrontPanel.Gtk.Container+ContainerChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            // Container child expander1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ejectButton = new Gtk.ToggleButton();
            this.ejectButton.CanFocus = true;
            this.ejectButton.Name = "ejectButton";
            this.ejectButton.UseUnderline = true;
            this.ejectButton.Label = Mono.Unix.Catalog.GetString("togglebutton1");
            this.hbox1.Add(this.ejectButton);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.ejectButton]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.powerButton = new Gtk.ToggleButton();
            this.powerButton.CanFocus = true;
            this.powerButton.Name = "powerButton";
            this.powerButton.UseUnderline = true;
            this.powerButton.Label = Mono.Unix.Catalog.GetString("togglebutton2");
            this.hbox1.Add(this.powerButton);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.powerButton]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.checkPause = new Gtk.CheckButton();
            this.checkPause.CanFocus = true;
            this.checkPause.Name = "checkPause";
            this.checkPause.Label = "Paused";
            this.checkPause.DrawIndicator = true;
            this.checkPause.UseUnderline = true;
            this.hbox1.Add(this.checkPause);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.checkPause]));
            w3.Position = 2;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.expander2 = new Gtk.Expander(null);
            this.expander2.CanFocus = true;
            this.expander2.Name = "expander2";
            this.expander2.Expanded = true;
            // Container child expander2.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.txtRomInfo = new Gtk.TextView();
            this.txtRomInfo.CanFocus = true;
            this.txtRomInfo.Name = "txtRomInfo";
            this.GtkScrolledWindow.Add(this.txtRomInfo);
            this.expander2.Add(this.GtkScrolledWindow);
            this.GtkLabel4 = new Gtk.Label();
            this.GtkLabel4.Name = "GtkLabel4";
            this.GtkLabel4.LabelProp = "ROM Information";
            this.GtkLabel4.UseUnderline = true;
            this.expander2.LabelWidget = this.GtkLabel4;
            this.vbox1.Add(this.expander2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.expander2]));
            w7.Position = 1;
            this.expander1.Add(this.vbox1);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("Control Panel");
            this.GtkLabel3.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel3;
            this.Add(this.expander1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
