// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.HPaned hpaned2;
    
    private Gtk.GLWidget glwidget2;
    
    private Gtk.VBox controlPanel;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.hpaned2 = new Gtk.HPaned();
        this.hpaned2.CanFocus = true;
        this.hpaned2.Name = "hpaned2";
        this.hpaned2.Position = 10;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.glwidget2 = new Gtk.GLWidget();
        this.glwidget2.Name = "glwidget2";
        this.glwidget2.DoubleBuffered = true;
        this.glwidget2.ColorBits = 24;
        this.glwidget2.AlphaBits = 8;
        this.glwidget2.DepthBits = 0;
        this.glwidget2.StencilBits = 0;
        this.hpaned2.Add(this.glwidget2);
        Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.glwidget2]));
        w1.Resize = false;
        // Container child hpaned2.Gtk.Paned+PanedChild
        this.controlPanel = new Gtk.VBox();
        this.controlPanel.Name = "controlPanel";
        this.controlPanel.Spacing = 6;
        this.hpaned2.Add(this.controlPanel);
        this.Add(this.hpaned2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
