// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkNes {
    
    
    public partial class VolumeWidget {
        
        private Gtk.Expander expander1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HScale hscale1;
        
        private Gtk.CheckButton chkMute;
        
        private Gtk.Label GtkLabel1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkNes.VolumeWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkNes.VolumeWidget";
            // Container child GtkNes.VolumeWidget.Gtk.Container+ContainerChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            // Container child expander1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hscale1 = new Gtk.HScale(null);
            this.hscale1.CanFocus = true;
            this.hscale1.Name = "hscale1";
            this.hscale1.Adjustment.Upper = 100;
            this.hscale1.Adjustment.PageIncrement = 10;
            this.hscale1.Adjustment.StepIncrement = 1;
            this.hscale1.Adjustment.Value = 75;
            this.hscale1.DrawValue = true;
            this.hscale1.Digits = 0;
            this.hscale1.ValuePos = ((Gtk.PositionType)(2));
            this.vbox1.Add(this.hscale1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.hscale1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.chkMute = new Gtk.CheckButton();
            this.chkMute.CanFocus = true;
            this.chkMute.Name = "chkMute";
            this.chkMute.Label = "Mute";
            this.chkMute.DrawIndicator = true;
            this.chkMute.UseUnderline = true;
            this.vbox1.Add(this.chkMute);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.chkMute]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.expander1.Add(this.vbox1);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = "Sound";
            this.GtkLabel1.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel1;
            this.Add(this.expander1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
