// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkNes {
    
    
    public partial class FrontPanel {
        
        private Gtk.Expander expander1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ToggleButton togglebutton1;
        
        private Gtk.ToggleButton togglebutton2;
        
        private Gtk.CheckButton checkbutton1;
        
        private Gtk.Expander expander2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView textview1;
        
        private Gtk.Label GtkLabel4;
        
        private Gtk.Label GtkLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkNes.FrontPanel
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkNes.FrontPanel";
            // Container child GtkNes.FrontPanel.Gtk.Container+ContainerChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            // Container child expander1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.togglebutton1 = new Gtk.ToggleButton();
            this.togglebutton1.CanFocus = true;
            this.togglebutton1.Name = "togglebutton1";
            this.togglebutton1.UseUnderline = true;
            this.togglebutton1.Label = Mono.Unix.Catalog.GetString("togglebutton1");
            this.hbox1.Add(this.togglebutton1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.togglebutton1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.togglebutton2 = new Gtk.ToggleButton();
            this.togglebutton2.CanFocus = true;
            this.togglebutton2.Name = "togglebutton2";
            this.togglebutton2.UseUnderline = true;
            this.togglebutton2.Label = Mono.Unix.Catalog.GetString("togglebutton2");
            this.hbox1.Add(this.togglebutton2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.togglebutton2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.checkbutton1 = new Gtk.CheckButton();
            this.checkbutton1.CanFocus = true;
            this.checkbutton1.Name = "checkbutton1";
            this.checkbutton1.Label = Mono.Unix.Catalog.GetString("checkbutton1");
            this.checkbutton1.DrawIndicator = true;
            this.checkbutton1.UseUnderline = true;
            this.hbox1.Add(this.checkbutton1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.checkbutton1]));
            w3.Position = 2;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.expander2 = new Gtk.Expander(null);
            this.expander2.CanFocus = true;
            this.expander2.Name = "expander2";
            this.expander2.Expanded = true;
            // Container child expander2.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.textview1 = new Gtk.TextView();
            this.textview1.CanFocus = true;
            this.textview1.Name = "textview1";
            this.GtkScrolledWindow.Add(this.textview1);
            this.expander2.Add(this.GtkScrolledWindow);
            this.GtkLabel4 = new Gtk.Label();
            this.GtkLabel4.Name = "GtkLabel4";
            this.GtkLabel4.LabelProp = Mono.Unix.Catalog.GetString("expander2");
            this.GtkLabel4.UseUnderline = true;
            this.expander2.LabelWidget = this.GtkLabel4;
            this.vbox1.Add(this.expander2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.expander2]));
            w7.Position = 1;
            this.expander1.Add(this.vbox1);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("Control Panel");
            this.GtkLabel.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel;
            this.Add(this.expander1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
