// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GtkNes {
    
    
    public partial class CheatView {
        
        private Gtk.Expander expander1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView cheatList;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Entry txtCheatCode;
        
        private Gtk.Button btnAddCheat;
        
        private Gtk.Button btnClearCheats;
        
        private Gtk.Label GtkLabel2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GtkNes.CheatView
            Stetic.BinContainer.Attach(this);
            this.Name = "GtkNes.CheatView";
            // Container child GtkNes.CheatView.Gtk.Container+ContainerChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            // Container child expander1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.cheatList = new Gtk.TreeView();
            this.cheatList.CanFocus = true;
            this.cheatList.Name = "cheatList";
            this.GtkScrolledWindow.Add(this.cheatList);
            this.vbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
            w2.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.txtCheatCode = new Gtk.Entry();
            this.txtCheatCode.CanFocus = true;
            this.txtCheatCode.Name = "txtCheatCode";
            this.txtCheatCode.IsEditable = true;
            this.txtCheatCode.InvisibleChar = '●';
            this.hbox1.Add(this.txtCheatCode);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.txtCheatCode]));
            w3.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnAddCheat = new Gtk.Button();
            this.btnAddCheat.CanFocus = true;
            this.btnAddCheat.Name = "btnAddCheat";
            this.btnAddCheat.UseUnderline = true;
            this.btnAddCheat.Label = Mono.Unix.Catalog.GetString("Add");
            this.hbox1.Add(this.btnAddCheat);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnAddCheat]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnClearCheats = new Gtk.Button();
            this.btnClearCheats.CanFocus = true;
            this.btnClearCheats.Name = "btnClearCheats";
            this.btnClearCheats.UseUnderline = true;
            this.btnClearCheats.Label = Mono.Unix.Catalog.GetString("Clear");
            this.hbox1.Add(this.btnClearCheats);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnClearCheats]));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.expander1.Add(this.vbox1);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("expander1");
            this.GtkLabel2.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel2;
            this.Add(this.expander1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
