// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.GLWidget glwidget2;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.VBox controlPanel;
    
    private Gtk.Label lblControls;
    
    private Gtk.VBox debugger;
    
    private Gtk.Label label2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 98;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.glwidget2 = new Gtk.GLWidget();
        this.glwidget2.Name = "glwidget2";
        this.glwidget2.DoubleBuffered = true;
        this.glwidget2.ColorBits = 24;
        this.glwidget2.AlphaBits = 8;
        this.glwidget2.DepthBits = 0;
        this.glwidget2.StencilBits = 0;
        this.hpaned1.Add(this.glwidget2);
        Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.glwidget2]));
        w1.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 1;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.controlPanel = new Gtk.VBox();
        this.controlPanel.Name = "controlPanel";
        this.controlPanel.Spacing = 6;
        this.notebook1.Add(this.controlPanel);
        // Notebook tab
        this.lblControls = new Gtk.Label();
        this.lblControls.Name = "lblControls";
        this.lblControls.LabelProp = Mono.Unix.Catalog.GetString("Controls");
        this.notebook1.SetTabLabel(this.controlPanel, this.lblControls);
        this.lblControls.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.debugger = new Gtk.VBox();
        this.debugger.Name = "debugger";
        this.debugger.Spacing = 6;
        this.notebook1.Add(this.debugger);
        Gtk.Notebook.NotebookChild w3 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.debugger]));
        w3.Position = 1;
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Debugging");
        this.notebook1.SetTabLabel(this.debugger, this.label2);
        this.label2.ShowAll();
        this.hpaned1.Add(this.notebook1);
        this.Add(this.hpaned1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
